In [1]:
%%capture
%run merging_data.ipynb

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# before dropping columns
merged_years['2017']

,City,status,Household Income,All,African American,American Indian,Hispanic/ Latinx,Pacific Islander,Asian,White,Domestic Unknown,Int'l,Female,Male,Other,Unknown,Measure Values
0,Alameda,Adm,131116,253.0,12.0,0.0,20.0,0.0,150.0,50.0,4.0,0.0,140.0,107.0,0.0,3.0,4.004111
1,Alameda,App,131116,339.0,24.0,0.0,28.0,0.0,188.0,67.0,6.0,0.0,176.0,151.0,0.0,0.0,4.001742
2,Alhambra,Adm,72406,224.0,0.0,0.0,16.0,0.0,196.0,0.0,4.0,0.0,137.0,77.0,0.0,5.0,3.791239
3,Alhambra,App,72406,399.0,5.0,0.0,62.0,0.0,317.0,0.0,6.0,0.0,231.0,155.0,0.0,8.0,3.789499
4,Anaheim,Adm,85133,452.0,5.0,0.0,181.0,0.0,156.0,79.0,0.0,0.0,275.0,164.0,0.0,0.0,3.864199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Whittier,App,91457,511.0,10.0,0.0,437.0,0.0,19.0,24.0,0.0,0.0,294.0,204.0,0.0,0.0,3.973521
274,Yorba Linda,Adm,151534,103.0,5.0,0.0,5.0,0.0,48.0,38.0,5.0,0.0,48.0,49.0,0.0,6.0,4.001650
275,Yorba Linda,App,151534,145.0,6.0,0.0,16.0,0.0,63.0,53.0,5.0,0.0,70.0,67.0,0.0,8.0,4.001650
276,Yuba City,Adm,59588,74.0,0.0,0.0,22.0,0.0,36.0,8.0,0.0,0.0,40.0,34.0,0.0,0.0,3.960135
277,Yuba City,App,59588,111.0,0.0,0.0,35.0,0.0,51.0,11.0,0.0,0.0,60.0,48.0,0.0,0.0,3.963658

In [4]:
for year in years:
    merged_years[year] = merged_years[year].drop(['American Indian', 'Pacific Islander', 'Domestic Unknown', 'Int\'l', 'Other', 'Unknown'], axis=1)

In [5]:
# after dropping columns
merged_years['2017']

,City,status,Household Income,All,African American,Hispanic/ Latinx,Asian,White,Female,Male,Measure Values
0,Alameda,Adm,131116,253.0,12.0,20.0,150.0,50.0,140.0,107.0,4.004111
1,Alameda,App,131116,339.0,24.0,28.0,188.0,67.0,176.0,151.0,4.001742
2,Alhambra,Adm,72406,224.0,0.0,16.0,196.0,0.0,137.0,77.0,3.791239
3,Alhambra,App,72406,399.0,5.0,62.0,317.0,0.0,231.0,155.0,3.789499
4,Anaheim,Adm,85133,452.0,5.0,181.0,156.0,79.0,275.0,164.0,3.864199
...,...,...,...,...,...,...,...,...,...,...,...
273,Whittier,App,91457,511.0,10.0,437.0,19.0,24.0,294.0,204.0,3.973521
274,Yorba Linda,Adm,151534,103.0,5.0,5.0,48.0,38.0,48.0,49.0,4.001650
275,Yorba Linda,App,151534,145.0,6.0,16.0,63.0,53.0,70.0,67.0,4.001650
276,Yuba City,Adm,59588,74.0,0.0,22.0,36.0,8.0,40.0,34.0,3.960135
277,Yuba City,App,59588,111.0,0.0,35.0,51.0,11.0,60.0,48.0,3.963658

Explanation for dropping the columns: As seen in the summary data, there's not much information on those particular groups in general, or they're too nondescriptive to be applied (for example, what is "Domestic Unknown"?). This decision was also informed by the heatmap of NaN values for the categories; for the dropped categories, most of the values were NaN.

In [6]:
# now, we know number of cities has stayed the same across all 8 years
# so we can create 3 new DataFrames: 2016-2019, 2020-2023, and all
for year in years:
    print(len(merged_years[year]))

278
278
278
278
278
278
278
278

In [22]:
# create new DataFrames merging every two rows
#
# before_covid    Contains merged data from 2016-2019, before COVID
# after_covid     Contains merged data from 2020-2023, after COVID
# all             Contains merged data across all 8 years

before_covid = pd.DataFrame(columns=['City', 'Income', 'GPA', 'All', 'African American', 'Hispanic/ Latinx', 'Asian', 'White', 'Female', 'Male'])
after_covid = pd.DataFrame(columns=['City', 'Income', 'GPA', 'All', 'African American', 'Hispanic/ Latinx', 'Asian', 'White', 'Female', 'Male'])
all = pd.DataFrame(columns=['City', 'Income', 'GPA', 'All', 'African American', 'Hispanic/ Latinx', 'Asian', 'White', 'Female', 'Male'])

before_years = ['2016', '2017', '2018', '2019']
after_years = ['2020', '2021', '2022', '2023']
categories = ['All', 'African American', 'Hispanic/ Latinx', 'Asian', 'White', 'Female', 'Male']

for idx in range(0, 277, 2):
    before_values = {}
    after_values = {}
    all_values = {}
    
    # city
    before_values['City'] = after_values['City'] = all_values['City'] = merged_years['2016'].iloc[idx]['City']

    # admitted proportions
    before_adm = before_app = after_adm = after_app = all_adm = all_app = 0

    for category in categories:
        for year in before_years:
            before_adm += merged_years[year].iloc[idx][category]
            before_app += merged_years[year].iloc[idx+1][category]
            all_adm += merged_years[year].iloc[idx][category]
            all_app += merged_years[year].iloc[idx+1][category]
            
        for year in after_years:
            after_adm += merged_years[year].iloc[idx][category]
            after_app += merged_years[year].iloc[idx+1][category]
            all_adm += merged_years[year].iloc[idx][category]
            all_app += merged_years[year].iloc[idx+1][category]

        if before_app == 0:
            before_app = 1
        if after_app == 0:
            after_app = 1
        if all_app == 0:
            all_app = 1
    
        before_values[category] = before_adm / before_app
        after_values[category] = after_adm / after_app
        all_values[category] = all_adm / all_app

    # weighted gpa
    before_total_adm = after_total_adm = before_gpa = after_gpa = all_total_adm = all_gpa = 0
    
    for year in before_years:
        before_total_adm += merged_years[year].iloc[idx]['All']
        all_total_adm += merged_years[year].iloc[idx]['All']
        before_gpa += merged_years[year].iloc[idx]['Measure Values'] * merged_years[year].iloc[idx]['All']
        all_gpa += merged_years[year].iloc[idx]['Measure Values'] * merged_years[year].iloc[idx]['All']
        
    for year in after_years:
        after_total_adm += merged_years[year].iloc[idx]['All']
        all_total_adm += merged_years[year].iloc[idx]['All']
        after_gpa += merged_years[year].iloc[idx]['Measure Values'] * merged_years[year].iloc[idx]['All']
        all_gpa += merged_years[year].iloc[idx]['Measure Values'] * merged_years[year].iloc[idx]['All']

    before_values['GPA'] = before_gpa / before_total_adm
    after_values['GPA'] = after_gpa / after_total_adm
    all_values['GPA'] = all_gpa / all_total_adm

    # average income over the years
    before_inc = after_inc = all_inc = 0
    
    for year in before_years:
        before_inc += merged_years[year].iloc[idx]['Household Income']
        all_inc += merged_years[year].iloc[idx]['Household Income']
        
    for year in after_years:
        after_inc += merged_years[year].iloc[idx]['Household Income']
        all_inc += merged_years[year].iloc[idx]['Household Income']

    before_values['Income'] = before_inc / 4
    after_values['Income'] = after_inc / 4
    all_values['Income'] = all_inc / 8

    before_concat = pd.DataFrame(before_values, index=[0])
    after_concat = pd.DataFrame(after_values, index=[0])
    all_concat = pd.DataFrame(all_values, index=[0])

    before_covid = pd.concat([before_covid, before_concat])
    after_covid = pd.concat([after_covid, after_concat])
    all = pd.concat([all, all_concat])

## Data across all years, aggregated

In [23]:
import statsmodels.api as sm 

X = all.drop(['All', 'City'], axis=1)
y = all['All']

model = sm.Logit(y, X)

result = model.fit()

Optimization terminated successfully.
         Current function value: 0.595606
         Iterations 5

In [24]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                    All   No. Observations:                  139
Model:                          Logit   Df Residuals:                      131
Method:                           MLE   Df Model:                            7
Date:                Sun, 09 Jun 2024   Pseudo R-squ.:                     inf
Time:                        11:14:27   Log-Likelihood:                -82.789
converged:                       True   LL-Null:                        0.0000
Covariance Type:            nonrobust   LLR p-value:                     1.000
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Income            6.235e-07   7.72e-06      0.081      0.936   -1.45e-05    1.58e-05
GPA                 -0.5563      0.637     -0.874      0.382      -1.804       0.692
African American     2.0355     28.275      0.072      0.943     -53.383      57.454
Hispanic/ Latinx    -1.1295     26.944     -0.042      0.967     -53.939      51.680
Asian               -0.7905     39.131     -0.020      0.984     -77.485      75.904
White                3.0806    119.604      0.026      0.979    -231.340     237.501
Female              -2.2205     72.955     -0.030      0.976    -145.209     140.768
Male                 3.2808    127.703      0.026      0.980    -247.013     253.574
====================================================================================
"""

## Data before COVID

In [25]:
import statsmodels.api as sm 

X = before_covid.drop(['All', 'City'], axis=1)
y = before_covid['All']

model = sm.Logit(y, X)

result = model.fit()

Optimization terminated successfully.
         Current function value: 0.619950
         Iterations 5

In [26]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                    All   No. Observations:                  139
Model:                          Logit   Df Residuals:                      131
Method:                           MLE   Df Model:                            7
Date:                Sun, 09 Jun 2024   Pseudo R-squ.:                  -10.23
Time:                        11:14:34   Log-Likelihood:                -86.173
converged:                       True   LL-Null:                       -7.6767
Covariance Type:            nonrobust   LLR p-value:                     1.000
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Income            5.605e-07   7.17e-06      0.078      0.938   -1.35e-05    1.46e-05
GPA                 -0.5464      0.535     -1.021      0.307      -1.595       0.502
African American     2.1205     22.854      0.093      0.926     -42.673      46.914
Hispanic/ Latinx     0.2171     22.650      0.010      0.992     -44.176      44.611
Asian               -0.0979     28.702     -0.003      0.997     -56.353      56.158
White               -0.2389     74.654     -0.003      0.997    -146.559     146.081
Female               1.8744     54.532      0.034      0.973    -105.006     108.755
Male                 0.3284     80.978      0.004      0.997    -158.385     159.042
====================================================================================
"""

## Data after COVID

In [27]:
after_covid.head()

,City,Income,GPA,All,African American,Hispanic/ Latinx,Asian,White,Female,Male
0,Alameda,131116.0,4.027053,0.735500,0.730054,0.730621,0.732016,0.734053,0.736446,0.734461
0,Alhambra,72406.0,3.951885,0.659788,0.657771,0.640764,0.660398,0.660398,0.667932,0.660333
0,Anaheim,85133.0,3.938044,0.629721,0.627057,0.617358,0.634589,0.627925,0.630482,0.628335
0,Antioch,100178.0,3.969630,0.691126,0.662618,0.671642,0.690476,0.691906,0.686458,0.691681
0,Apple Valley,56187.0,3.975468,0.691558,0.677843,0.674326,0.685341,0.689280,0.688020,0.689462

In [28]:
import statsmodels.api as sm 

X = after_covid.drop(['All', 'City'], axis=1)
y = after_covid['All']

model = sm.Logit(y, X)

result = model.fit()

Optimization terminated successfully.
         Current function value: 0.565546
         Iterations 5

In [29]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                    All   No. Observations:                  139
Model:                          Logit   Df Residuals:                      131
Method:                           MLE   Df Model:                            7
Date:                Sun, 09 Jun 2024   Pseudo R-squ.:                     inf
Time:                        11:14:45   Log-Likelihood:                -78.611
converged:                       True   LL-Null:                        0.0000
Covariance Type:            nonrobust   LLR p-value:                     1.000
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Income            6.022e-07   7.92e-06      0.076      0.939   -1.49e-05    1.61e-05
GPA                 -0.5606      0.602     -0.931      0.352      -1.741       0.620
African American     2.1651     28.561      0.076      0.940     -53.814      58.144
Hispanic/ Latinx    -1.3751     26.352     -0.052      0.958     -53.024      50.274
Asian               -0.4877     37.603     -0.013      0.990     -74.188      73.213
White                0.7132    101.911      0.007      0.994    -199.029     200.455
Female              -2.8047     52.990     -0.053      0.958    -106.663     101.053
Male                 6.1001    108.765      0.056      0.955    -207.075     219.275
====================================================================================
"""